POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test", 
    "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "noName": "noname",
    "noNumber": "noNumber"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "name"
}